### ISSUE TITLE
startswith/endswith filters seems to be broken

### ISSUE THREAD

**Issue by janedoe-lab** [kruschid/refine-pocketbase#10]
Per https://pocketbase.io/docs/api-records/#listsearch-records to run a LIKE filter, one need to use `~` operand.

But refine-pocketbase seems to use `=` for start/ends with filters - https://github.com/kruschid/refine-pocketbase/blob/24b0283286d3d9a56ca3b5cb2dfb8ea836c15805/lib/src/filters.ts#L96

**Comment by janedoe-lab** [comment]
Temp fix is to replace `endswith`/`startswith` with `contains` and adding `%` appropriately.

**Comment by kruschid** [comment]
No idea how this could have happend, but it seems that you are the first person who uses this filter. :-)

Thank you for reporting. Here the fix: [v0.3.1](https://github.com/kruschid/refine-pocketbase/releases/tag/v0.3.1)

Let me know if you find more problems. Thank you.
