### ISSUE TITLE
support for expand via meta props

### ISSUE THREAD

**Issue by kruschid** [kruschid/refine-pocketbase#2]
Sample code provided by @fspijkerman via discord:

``` ts
getList: async ({ resource, pagination, filters, meta, sorters }) => {
  const { current = 1, pageSize = 10 } = pagination ?? {};
  const generatedFilter = generateFilter(filters);
  const result = await pocketBaseClient.collection(resource).getList(current, pageSize, {
    filter: generatedFilter,
    expand: meta?.expand,
    sort: sorters?.flatMap( (x) => `${x.order == "asc" ? "+" : "-"}${x.field.replace("expand.", "")}`).join(",") ?? ""
  });

  if (result.items) {
    return {
      data: result.items,
      total: result.totalItems,
    } as any;
  }

  return {
    data: [],
    total: 0,
  } as any;
},
getOne: async ({ resource, id, meta }) => {
  if (id == undefined) {
    return { data: undefined }
  }

  try {
    const result = await pocketBaseClient.collection(resource).getOne(id as string, {
      expand: meta?.expand ?? null,
      fields: meta?.fields?.join(",") ?? "*",
    });

    if (result) {
      return {
        data: result as any,
      };
    }

    return {
      data: undefined
    }
  } catch (e: any) {
    const error: HttpError = {
      message: e.response.message,
      statusCode: e.status as number,
    };
    return Promise.reject(error);
  }
},
```

**Comment by mckay115** [comment]
I was wondering if the same approach or similar enhancements could be applied to handle file uploads more seamlessly.

Currently, PocketBase requires `FormData` for file uploads, but the `create` and `update` methods in `dataProvider` don’t directly support detecting and processing file fields. This makes it necessary to either:
- Use the PocketBase SDK directly for file uploads, bypassing `dataProvider`, or
- Modify the `dataProvider` locally to handle `FormData`.

Would it make sense to enhance the `dataProvider` to detect and handle file uploads automatically?

**Comment by kruschid** [comment]
Hi @mckay115, thank you for the question. 🙏 

You shouldn't have any problems to pass your payload to the `dataProvider` the same way as you would with PocketBase SDK. Under the hood the `dataProvider` uses the SDK methods without modifying your payload objects.

create:
https://github.com/kruschid/refine-pocketbase/blob/5aed773d0ed8465fd91f6d4a615f228fe2f9944f/lib/src/dataProvider.ts#L75

update:
https://github.com/kruschid/refine-pocketbase/blob/5aed773d0ed8465fd91f6d4a615f228fe2f9944f/lib/src/dataProvider.ts#L92

No workarounds needed. You can follow the description in the [PocketBase JavaScript SDK Readme](https://github.com/pocketbase/js-sdk?tab=readme-ov-file#file-upload). However I haven't tested file upload myself yet. Please feel free to open a new issue if you encounter any problems.

I will close this issue since the original topic was the expand prop and that feature is implemented now. Here the description: https://github.com/kruschid/refine-pocketbase/tree/8244124bc97058a40d16987781b1267a338840a9?tab=readme-ov-file#the-meta-properties-fields-and-expand
