### ISSUE TITLE
Does refine-pocketbase supports Pocketbase v0.23+ ?

### ISSUE THREAD

**Issue by janedoe-lab** [kruschid/refine-pocketbase#9]
Looking at Pocketbase project changelog, they mention significant changes in v0.23+. I see mention of `pocketbase` npm module at version `0.21.5` in `package-lock.json`.

Before diving in, wanted to check if someone already tested `refine-pocketbase` with v0.23+ of pocketbase, and how big/small is commitment to upgrade it to the latest js sdk? Or maybe it just works after bumping the dependency?

**Comment by kruschid** [comment]
Hi, don't worry about the older SDK version in the lockfile. The refine adapters in this repo are not affected by the [breaking changes in SDK@0.22](https://github.com/pocketbase/js-sdk/blob/master/CHANGELOG.md#0220). A bunch of props are marked as deprecated now but I'm preparing a fix for that. That means you can start using the library and update later. Thanks for the question. If you find any problems let me know.

**Comment by kruschid** [comment]
[v0.3.0](https://github.com/kruschid/refine-pocketbase/releases/tag/v0.3.0)
